-- Lab 6: run this in Supabase SQL Editor.

create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  slug text not null unique,
  title text not null,
  category text not null,
  contributor text not null,
  place text not null,
  period text not null,
  featured_object text not null,
  excerpt text not null,
  memory text not null,
  learning_method text not null,
  reflection text not null,
  status text not null default 'published' check (status in ('draft', 'review', 'published')),
  created_at timestamptz not null default now()
);

alter table public.entries enable row level security;

drop policy if exists "Anyone can read published entries" on public.entries;
create policy "Anyone can read published entries"
on public.entries
for select
to anon, authenticated
using (status = 'published' or (select auth.uid()) = owner_id);

drop policy if exists "Authenticated users can create their entries" on public.entries;
create policy "Authenticated users can create their entries"
on public.entries
for insert
to authenticated
with check ((select auth.uid()) = owner_id);

drop policy if exists "Owners can update their entries" on public.entries;
create policy "Owners can update their entries"
on public.entries
for update
to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

drop policy if exists "Owners can delete their entries" on public.entries;
create policy "Owners can delete their entries"
on public.entries
for delete
to authenticated
using ((select auth.uid()) = owner_id);

-- Needed if your project has new Data API table exposure behavior.
grant usage on schema public to anon, authenticated;
grant select on public.entries to anon, authenticated;
grant insert, update, delete on public.entries to authenticated;
grant usage, select on sequence public.entries_id_seq to authenticated;

insert into public.entries (
  owner_id,
  slug,
  title,
  category,
  contributor,
  place,
  period,
  featured_object,
  excerpt,
  memory,
  learning_method,
  reflection,
  status
) values
(
  '7870004e-7f84-4440-bb7c-b9daaaf066ca',
  'learning-from-one-shared-textbook',
  'Learning From One Shared Textbook',
  'Learning Materials',
  'Sokha',
  'Kampong Cham Province',
  '1984-1988',
  'A Khmer-language textbook shared among several students and a handwritten exercise notebook.',
  'A memory of classmates sharing one textbook, copying lessons by hand, and protecting notebooks as their main study record.',
  'During lessons, students followed the teacher''s writing on the chalkboard and copied everything carefully into their notebooks. When there were not enough books, classmates sat together and took turns reading from the same textbook. Missing a lesson was difficult because the notebook was often the only complete record a student could use at home.',
  'Information came mainly from teachers, textbooks, older relatives, and classmates. Examination preparation involved rereading handwritten notes, copying exercises again, memorizing important passages, and reciting answers with friends.',
  'Digital tools make information easier to find today, but students should remember the patience, cooperation, and respect for learning materials that earlier students needed.',
  'published'
),
(
  '7870004e-7f84-4440-bb7c-b9daaaf066ca',
  'the-journey-to-secondary-school',
  'The Journey to Secondary School',
  'Student Stories',
  'Srey Mom',
  'Siem Reap Province',
  '2001-2006',
  'A collection of handwritten lesson notes and an old examination paper kept after leaving school.',
  'A student story about traveling from village to school and relying on teachers, notebooks, and classmates for study.',
  'Reaching secondary school required traveling from the village each morning. In class, the teacher explained lessons orally and used chalkboard diagrams while students copied the information. After school, classmates sometimes reviewed difficult exercises together because books and other sources of information were limited.',
  'Students depended on classroom explanations, printed textbooks, borrowed study books, and help from classmates. They prepared for examinations by reviewing notebooks, practicing previous exercises, and asking teachers to explain topics they did not understand.',
  'Students now have quick access to videos, search engines, and AI, but technology should support careful study rather than replace discussion, practice, and help from teachers.',
  'published'
),
(
  '7870004e-7f84-4440-bb7c-b9daaaf066ca',
  'lessons-under-the-house-after-school',
  'Lessons Under the House After School',
  'Community Learning',
  'Chantha',
  'Takeo Province',
  '1992-1997',
  'A slate board, chalk pieces, and copied vocabulary lists used for extra practice after class.',
  'A community learning memory where older students helped younger children practice reading, spelling, and multiplication.',
  'After the regular school day, several children gathered under a neighbor''s wooden house to repeat difficult lessons. An older student helped younger children read Khmer words aloud, copy multiplication tables, and correct spelling mistakes before the next class.',
  'Learning depended on repetition, peer help, and family encouragement. Students practiced by copying the same words many times, reading aloud together, and asking older relatives or neighbors to explain confusing lessons.',
  'The story shows that learning was not limited to the classroom. Community support helped students continue studying even when school materials were simple.',
  'published'
),
(
  '7870004e-7f84-4440-bb7c-b9daaaf066ca',
  'a-teachers-chalkboard-diagrams',
  'A Teacher''s Chalkboard Diagrams',
  'Teacher Memories',
  'Vichea',
  'Phnom Penh',
  '1998-2003',
  'A lesson notebook filled with hand-drawn science diagrams copied from the classroom chalkboard.',
  'A teacher memory about chalkboard drawings becoming the main image source for science study before online media.',
  'The teacher drew diagrams slowly on the chalkboard while students copied each line into their notebooks. Because printed pictures were not always available, the drawing itself became the main study guide for homework and examination review.',
  'Students listened carefully, copied the board, asked short questions during class, and reviewed their notebooks at home. Accuracy mattered because one unclear drawing could make the lesson hard to understand later.',
  'Before online images and videos, a teacher''s explanation and chalkboard work shaped how students imagined subjects they could not see directly.',
  'published'
),
(
  '7870004e-7f84-4440-bb7c-b9daaaf066ca',
  'borrowed-books-before-exams',
  'Borrowed Books Before Exams',
  'Exam Preparation',
  'Dara',
  'Battambang Province',
  '2004-2009',
  'A borrowed study book passed between classmates during the week before examinations.',
  'An exam-season memory about borrowed books, copied examples, and classmates sharing scarce study materials.',
  'When examination season came, students borrowed study books from friends, cousins, or older students. They copied useful examples into notebooks quickly because the books had to be returned for someone else to study.',
  'Preparation involved sharing scarce materials, memorizing model answers, solving exercises repeatedly, and comparing notes with classmates after school.',
  'The memory highlights cooperation and pressure. Students had fewer resources, so sharing and time management became important parts of learning.',
  'published'
)
on conflict (slug) do update set
  owner_id = excluded.owner_id,
  title = excluded.title,
  category = excluded.category,
  contributor = excluded.contributor,
  place = excluded.place,
  period = excluded.period,
  featured_object = excluded.featured_object,
  excerpt = excluded.excerpt,
  memory = excluded.memory,
  learning_method = excluded.learning_method,
  reflection = excluded.reflection,
  status = excluded.status;

-- Logged-out write test. Expected result: permission denied / RLS violation.
-- Run these 3 lines separately after the seed succeeds if you want screenshot proof.
-- set local role anon;
-- insert into public.entries (owner_id, slug, title, category, contributor, place, period, featured_object, excerpt, memory, learning_method, reflection)
-- values ('7870004e-7f84-4440-bb7c-b9daaaf066ca', 'logged-out-rls-test', 'Logged out RLS test', 'Test', 'Test', 'Test', 'Test', 'Test', 'Test', 'Test', 'Test', 'Test');
